[Youtube]
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
arch = "arm64-v8a"
excluded-patches = "'Alternative thumbnails' 'Return YouTube Dislike' 'Custom branding'"

[Instagram]
patches-source = "crimera/piko"
uptodown-dlurl = "https://instagram.en.uptodown.com/android"
arch = "arm64-v8a"

[Pinterest]
patches-source = "binarymend/morphe-patches"
uptodown-dlurl = "https://pinterest.en.uptodown.com/android"
arch = "arm64-v8a"
